name: CI

on: push

jobs:
  build:
    name: Build
    runs-on: [self-hosted, Linux, ForksForTest, Ubuntu19.10]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
