name: CI

on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container: 
      image: node:14.2
      ports: 
        - 8080:80
      volumes:
        - /home/linuxbrew:/_rh/linuxbrew
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Check env
        run: |
          echo "check the custom volumes" > /_rh/linuxbrew/test.txt
          cat /_rh/linuxbrew/test.txt
          echo "===================================================="
          echo "List all environment variables:"
          printenv
