name: CI

on: push

jobs:
  build:
    name: Build
    runs-on: [self-hosted, Linux, ForksForTest, Ubuntu19.10]
    container: 
      image: node:14.2
      ports: 
        - 8080:80
      volumes:
        - /home/var/www/html:volume/var_www_html
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Check env
        run: |
          echo "List All Environment Variables:"
          printenv
