name: CI

on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container: 
      image: node:14.2
      ports: 
        - 8080:80
#      volumes:
#        - /home/var/www/html:volume/var_www_html
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Check env
        run: |
          echo "List All Environment Variables:"
          printenv

  job2:
    name: View dir
    runs-on: ubuntu-latest
    steps:
      - name: View dir
        run: ls -R /home
